version: "3.7"
services:
  app_db:
    build:
      context: .
      dockerfile: ./db.dockerfile
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: auction
      POSTGRES_USER: argadev
      POSTGRES_PASSWORD: 123456